name: Benchmark
on: [push, pull_request]

env:
  DOCKER_BUILDKIT: 1

jobs:
  hello-bench:
    runs-on: ubuntu-20.04
    name: HelloBench
    env:
      BENCHMARK_LOG_DIR: ${{ github.workspace }}/log/
      BENCHMARK_RESULT_DIR: ${{ github.workspace }}/benchmark/
      BENCHMARK_REGISTRY: ghcr.io
      BENCHMARK_USER: ktock
      BENCHMARK_TARGETS: tomcat:10.0.0-jdk15-openjdk-buster python:3.7 gcc:9.2.0 rethinkdb:2.3.6
      BENCHMARK_SAMPLES_NUM: 5
      BENCHMARK_PERCENTILE: 95
      BENCHMARK_PERCENTILES_GRANULARITY: 25
    steps:
    - name: Install tools
      run: |
          sudo apt-get update && sudo apt-get --no-install-recommends install -y gnuplot
          pip install numpy
    - uses: actions/checkout@v2
    - name: Prepare directories
      run: mkdir "${BENCHMARK_RESULT_DIR}" "${BENCHMARK_LOG_DIR}"
    - name: Get instance information
      run: |
          curl -H "Metadata:true" "http://169.254.169.254/metadata/instance?api-version=2019-11-01" | \
          jq '{ location : .compute.location, vmSize : .compute.vmSize }' | \
          tee ${{ env.BENCHMARK_RESULT_DIR }}/instance.json
    - name: Run benchmark
      run: make benchmark
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: benchmarking-result
        path: ${{ env.BENCHMARK_RESULT_DIR }}
