name: Buildkit
on: [push, pull_request]

jobs:
  buildkit-integration:
    runs-on: ubuntu-20.04
    name: BuildkitIntegration
    env:
      BENCHMARK_LOG_DIR: ${{ github.workspace }}/log/
      BENCHMARK_RESULT_DIR: ${{ github.workspace }}/benchmark/
      BENCHMARK_SAMPLES_NUM: 3
      BENCHMARK_PERCENTILE: 100
      BENCHMARK_PERCENTILES_GRANULARITY: 50
    steps:
    - name: Install tools
      run: |
          sudo apt-get --no-install-recommends install -y gnuplot
          pip install numpy
    - uses: actions/checkout@v2
    - name: Prepare output directories
      run: mkdir "${BENCHMARK_RESULT_DIR}" "${BENCHMARK_LOG_DIR}"
    - name: Get instance information
      run: |
          curl -H "Metadata:true" "http://169.254.169.254/metadata/instance?api-version=2019-11-01" | \
          jq '{ location : .compute.location, vmSize : .compute.vmSize }' | \
          tee ${{ env.BENCHMARK_RESULT_DIR }}/instance.json
    - name: Run benchmark
      run: ./script/buildkit/test.sh
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: buildkit-benchmarking-result
        path: ${{ env.BENCHMARK_RESULT_DIR }}
