name: Tests
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Measure
    steps:
    - uses: actions/checkout@v2
    - name: Measure
      run: cd ./script/optimize-bench && ./test.sh
