name: Tests
on:
  push:
  pull_request:

env:
  DOCKER_BUILDKIT: 1

jobs:
  test-cri-cri-o:
    runs-on: ubuntu-22.04
    name: test
    strategy:
      fail-fast: false
    steps:
    - name: Install the latest docker
      run: |
        sudo apt-get remove moby-cli moby-engine
        wget -O get-docker.sh https://get.docker.com
        sh get-docker.sh
    - uses: actions/checkout@v4
    - name: Validate CRI-O through CRI
      env:
        DOCKER_BUILD_ARGS: "--build-arg=RUNC_VERSION=v1.0.3"
        METADATA_STORE: memory
      run: |
        ./script/cri-o-restart/test.sh 
