name: Demo
on: [push, pull_request]

env:
  DOCKER_BUILDKIT: 1
  DEMO_RESULT_DIR: ${{ github.workspace }}/demo/

jobs:
  k3sdemo:
    runs-on: ubuntu-20.04
    name: K3SDemo
    steps:
    - name: Install k3d and argo
      run: |
        wget -q -O - https://raw.githubusercontent.com/rancher/k3d/v4.4.4/install.sh | bash
        curl -sLO https://github.com/argoproj/argo/releases/download/v3.0.4/argo-linux-amd64.gz
        gunzip argo-linux-amd64.gz
        chmod +x argo-linux-amd64
        sudo mv ./argo-linux-amd64 /usr/local/bin/argo
        sudo chown root:root /usr/local/bin/argo
        argo version
    - uses: actions/checkout@v2
    - name: Run demo
      run: ./script/k3sdemo/demo.sh
    - uses: actions/upload-artifact@v1
      if: ${{ always() }}
      with:
        name: demo-result
        path: ${{ env.DEMO_RESULT_DIR }}
