name: Tests
on: [push, pull_request]

env:
  DOCKER_BUILDKIT: 1

jobs:
  integration:
    runs-on: ubuntu-18.04
    name: Integration
    steps:
    - name: Install htpasswd for setting up private registry
      run: sudo apt-get update -y && sudo apt-get --no-install-recommends install -y apache2-utils
    - uses: actions/checkout@v2
    - name: Run integration test
      run: make integration
