name: Curl
on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    name: curl to repos
    env:
      GHCR_REPO: stargz-containers/python
      DOCKER_REPO: ktokunaga/python
      TARGET_BLOB: sha256:d1227b580b0e22493a4a286295606753fd5999db8b81df9082ced4b51d122406
    steps:
    - name: Get instance information
      run: |
          curl -H "Metadata:true" "http://169.254.169.254/metadata/instance?api-version=2019-11-01" | \
          jq '{ location : .compute.location, vmSize : .compute.vmSize }'
    - name: curl to ghcr.io
      run: |
          LOCATION=$(curl -v -H "Range: bytes=0-1" -H "Authorization: $(curl https://ghcr.io/token?scope=repository:${{ env.GHCR_REPO }}:pull | jq -r '.token')" https://ghcr.io/v2/${{ env.GHCR_REPO }}/blobs/${{ env.TARGET_BLOB }} 2>&1 | grep Location | sed -E 's/.*(http.*)/\1/g' | sed -e "s/[\r\n]\+//g")
          for i in {1..3}; do time curl -H "Range: bytes=0-1" "${LOCATION}" ; done
    - name: curl to docker.io
      run: |
          LOCATION=$(curl -v -H "Range: bytes=0-1" -H "Authorization: Bearer $(curl "https://auth.docker.io/token?service=registry.docker.io&scope=repository:${{ env.DOCKER_REPO }}:pull" | jq -r '.access_token')" https://registry-1.docker.io/v2/${{ env.DOCKER_REPO }}/blobs/${{ env.TARGET_BLOB }} 2>&1 | grep Location | sed -E 's/.*(http.*)/\1/g' | sed -e "s/[\r\n]\+//g")
          for i in {1..3}; do time curl -H "Range: bytes=0-1" "${LOCATION}" ; done
